name: dry-container
codacy_id: 227509c9034340b493f769f6277f4ecb
gemspec:
  authors: ["Andy Holland"]
  email: ["andyholland1991@aol.com"]
  summary: "A simple, configurable object container implemented in Ruby"
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [concurrent-ruby, "~> 1.0"]
